#!perl

# LICENSE: GNU GENERAL PUBLIC LICENSE GPL3.0
# Joseph Ryan <joseph.ryan@whitney.ufl.edu>

use strict;
use warnings;
use JFR::Fasta;
use Data::Dumper;

our $VERSION = 1.0;

our $FILE = $ARGV[0] or die "usage: $0 FASTA MINLEN\n";
our $MIN_LEN = $ARGV[1] or die "usage: $0 FASTA MINLEN\n";

MAIN: {
    my $fp = JFR::Fasta->new($FILE);
    my @seqs = ();
    while (my $rec = $fp->get_record()) {
        next unless (length($rec->{'seq'}) >= $MIN_LEN);
        push @seqs, [$rec->{'def'},$rec->{'seq'}];
    }
    foreach my $ra_s (sort {length($b->[1]) <=> length($a->[1])} @seqs) {
        print "$ra_s->[0]\n$ra_s->[1]\n";
    }
}
